import image from '../assets/images.png'

export const items = [
  { id: 1, name: 'Helvie Etmawati Gae, SKM', description: 'Kepala Puskesmas Wuasa',jabatan:'Administrator Kesehatan Madya', image: image },
  { id: 2, name: 'Noli Tagora, SKM', description: 'PJ Kecacingan',jabatan:'Administrator Kesehatan', image: image },
  { id: 3, name: 'Stien Towaki, SKM', description: 'PJ Batra',jabatan:'Administrator Kesehatan', image: image },
  { id: 4, name: 'Nini Yunita Larapos, SKM', description: 'PJ Klinik Gigi',jabatan:'Administrator Kesehatan', image: image },
  { id: 5, name: 'Yubtan Tangkoro', description: 'Petugas Schistosomiasis',jabatan:'Pengadministrasian Umum', image: image },
  { id: 6, name: 'Meni Pau', description: 'Petugas Apotik',jabatan:'Pengadministrasian Umum', image: image },
  { id: 7, name: 'Chobert Gatra Eleasar Abu', description: 'PJ Loket',jabatan:'Pengadministrasian Umum', image: image },
  { id: 8, name: 'Bernad Roreng', description: 'Kesling',jabatan:'Pengadministrasian Umum', image: image },
  { id: 9, name: 'Cerni Tolu', description: 'Petugas Schistosomiasis',jabatan:'Pengadministrasian Umum', image: image },
  { id: 10, name: 'Rosda', description: 'Staf TU',jabatan:'Pengadministrasian Umum', image: image },
  
  // Jajaran Dokter
  { id: 11, name: 'drg. Diah Ayu Lestari A.M.', description: 'Dokter Gigi',jabatan:'Dokter Gigi Ahli Pertama', image: image },
  { id: 12, name: 'dr. David Matthew Toding', description: 'Dokter',jabatan:'Dokter', image: image },
  
  // Jajaran Perawat
  { id: 13, name: 'Agus Salim Suali, S.Kep.Ns', description: 'PJ Gudang Obat',jabatan:'Perawat Ahli', image: image },
  { id: 14, name: 'Ramabay Palanti', description: 'PJ Ispa',jabatan:'Perawat Penyelia', image: image },
  { id: 15, name: 'Menis Boka', description: 'PJ Lansia',jabatan:'Perawat Penyelia', image: image },
  { id: 16, name: 'Irmayanti Lage, A.Md.Kep', description: 'PJ Kesehatan Jiwa',jabatan:'Perawat Penyelia', image: image },
  { id: 17, name: 'Paulus Massang, Amk', description: 'Petugas Schistosomiasis',jabatan:'Perawat Penyelia', image: image },
  { id: 18, name: 'Frida O. Wantuk, A.Md.Kep', description: 'PJ PTM',jabatan:'Perawat Penyelia', image: image },
  { id: 19, name: 'Meylani Selvia Lewo, S.Kep', description: 'PJ Lansia',jabatan:'Perawat Penyelia', image: image },
  { id: 20, name: 'Retslyn Mysna T., A.Md.Kep', description: 'PJ Imunisasi dan Malaria',jabatan:'Perawat Penyelia', image: image },
  { id: 21, name: 'Nia Duhriyah Sair, Amk', description: 'PJ UKS',jabatan:'Perawat Pelaksana', image: image },
  
  // Jajaran Bidan
  { id: 22, name: 'Marlisna Tolibo, SST', description: 'Kepala Ruangan Kamar Bersalin',jabatan:'Bidan Ahli', image: image },
  { id: 23, name: 'Ketty Wahyuni, S.Tr.Keb', description: 'PJ KB',jabatan:'Bidan Ahli Muda', image: image },
  { id: 24, name: 'Herliyanti Br. Sembiring, A.Md.Keb', description: 'Pengelola JKN',jabatan:'Bidan Ahli', image: image },
  { id: 25, name: 'Firginia Nelloh, A.Md.Keb', description: 'Staf Kamar Bersalin',jabatan:'Bidan Pelaksana', image: image },
  { id: 26, name: 'Sunariarti, S.Tr.Keb', description: 'KTU dan PJ Hepatitis',jabatan:'Bidan Ahli Pertama', image: image },
  { id: 27, name: 'Agustin Susanti Agnes Lakengke, A.Md.Keb', description: 'PJ HIV',jabatan:'Bidan Ahli Pertama', image: image },
  { id: 28, name: 'Agusdiana, A.Md.Keb', description: 'PJ Kespro',jabatan:'Bidan Ahli Pertama', image: image },
  { id: 29, name: 'Rahal Y. Sandingku, A.Md.Keb', description: 'Pengelola BOK dan PJ Remaja',jabatan:'Bidan Pelaksana Lanjutan', image: image },
  { id: 30, name: 'Darmi Susianti, A.Md.Keb', description: 'PJ Ibu',jabatan:'Bidan Pelaksana', image: image },
  { id: 31, name: 'Martina Bonggadika, A.Md.Keb', description: 'Bidan Desa Bongi-bongi',jabatan:'Bidan Pelaksana', image: image },
  { id: 32, name: 'Vivin Sandini Boka, A.Md.Keb', description: 'Bidan Koordinator Surveilens',jabatan:'Bidan Pelaksana', image: image },
  { id: 33, name: 'Nensi Indriani Mangki, A.Md.Keb', description: 'PJ Anak',jabatan:'Bidan Pelaksana', image: image },
  { id: 34, name: 'Elen Leomi Tengkow, SKM', description: 'PJ Promkes/Ketua UKM',jabatan:'Penyuluh Ahli', image: image },
  { id: 35, name: 'Nurul Istiqomah, A.Md.Keb', description: 'Bidan Desa Banyusari',jabatan:'Bidan', image: image },
  { id: 36, name: 'Deis Natalia Sengko, A.Md.Keb ', description: 'Bidan Desa Wuasa',jabatan:'Bidan', image: image },
  { id: 37, name: 'Wahyuni, A.Md.Keb', description: 'Bidan Desa Kaduwasa',jabatan:'Bidan', image: image },
  { id: 38, name: 'Vinario Tunde, A.Md.Keb', description: 'Bidan Desa Watumaeta',jabatan:'Bidan', image: image },
  { id: 39, name: "Rahma Mu'in, S.Tr.Keb", description: 'Staf Kamar Bersalin',jabatan:'Bidan', image: image },
  { id: 40, name: "Rina Astuti, A.Md.Keb", description: 'Bidan Desa Alitupu',jabatan:'Bidan', image: image },
  { id: 41, name: "Dini Sheilawaty Malaum, A.Md.Gz", description: 'PJ Program Gizi',jabatan:'Gizi', image: image },
  { id: 42, name: "Jhane Amelia Mpolada, SKM", description: 'Petugas Loket',jabatan:'Kesmas (Epidemiologi)', image: image },
  { id: 43, name: "Steward Guru, A.Md.Kep", description: 'Staf Rawat Inap',jabatan:'Perawat', image: image },
  { id: 44, name: "Marten Wentuk, S.Kep.Ns", description: 'Petugas Imunisasi',jabatan:'Perawat', image: image },
  { id: 45, name: "Zulfitriani Mustamar", description: 'Petugas Loket',jabatan:'Perawat', image: image },
  { id: 46, name: "Rifka Mellu, A.Md.Keb", description: 'Staf Kamar Bersalin',jabatan:'Bidan', image: image },
  { id: 47, name: "Muhammad Rivail, S.Kep.Ns", description: 'Driver Ambulance',jabatan:'Perawat', image: image },
  { id: 48, name: "Ns.Yuliana Mompewa, S.Kep", description: 'Staf Rawat Inap',jabatan:'Perawat', image: image },
  { id: 49, name: "Ribka Yanti, A.Md.Kep", description: 'Staf UGD',jabatan:'Perawat', image: image },
  { id: 50, name: "Nazaruddin Jamal, A.L, S.Kep", description: 'Staf Rawat Inap',jabatan:'Perawat', image: image },
  { id: 51, name: "Ansar Ramli, A.Md.Kep", description: 'Staf UGD',jabatan:'Perawat', image: image },
  { id: 52, name: "Sapniel Barusu, SKM", description: 'Petugas Schistosomiasis',jabatan:'Kesmas (Kesling)', image: image },
  { id: 53, name: "Cicilia Darminta Mondolu, SKM", description: 'Petugas Loket',jabatan:'Kesmas (Epidemiologi)', image: image },
  { id: 54, name: "Mira Rezky Towesu, A.Md.Kes", description: 'Petugas Lab',jabatan:'Analis', image: image },
  { id: 55, name: "Innda Yuliastri Warani, A.Md.Kep", description: 'Staf Rawat Inap',jabatan:'Perawat', image: image },
  { id: 56, name: "Steffi Olga Danes Kareba, A.Md.Keb", description: 'Bidan Desa Sedoa',jabatan:'Bidan', image: image },
  { id: 57, name: "Junein Peangka, A.Md.Kep", description: 'Perawat Desa Dongi-dongi',jabatan:'Perawat', image: image },
  { id: 58, name: "Lucy Sherly Wanda Towaki, A.Md.Keb", description: 'Bidan Desa Dodolo',jabatan:'Bidan', image: image },
  { id: 59, name: "Imelda Boka, A.Md.Far", description: 'PJ Apotik',jabatan:'Farmasi', image: image },
  { id: 60, name: "Eka Rahma, A.Md.Kep", description: 'Staf Rawat Inap',jabatan:'Perawat', image: image },
  { id: 61, name: "Iis Yuliana Sumampouw, A.Md.Keb", description: 'Staf Kamar Bersalin',jabatan:'Bidan', image: image },
  { id: 62, name: "Alfina Nindi, SKM", description: 'Petugas Lab',jabatan:'Kesmas / Epidemiologi', image: image },
  { id: 63, name: "Ronal Abe", description: 'Schistosomiasis',jabatan:'K2 / Schistosomiasis', image: image },
  { id: 64, name: "Marsianus Ampulembang", description: 'Staf Lab Schistosomiasis',jabatan:'Staf Lab Schistosomiasis', image: image },
  { id: 65, name: "Samsudin", description: 'Staf Lab Schistosomiasis',jabatan:'Staf Lab Schistosomiasis', image: image },
  { id: 66, name: "Rajab", description: 'Staf Lab Schistosomiasis',jabatan:'Staf Lab Schistosomiasis', image: image },
  { id: 67, name: "Moh. Irsan, A.Md.Kep", description: 'Staf Lab Schistosomiasis',jabatan:'Staf Lab Schistosomiasis', image: image },
  { id: 68, name: "Fauziah Hasan, S.Tr.Kes", description: 'Kesling',jabatan:'Kesling', image: image },
  { id: 69, name: "Ribka Grasela Bungkahi, Amd.Kes", description: 'ATLM',jabatan:'ATLM', image: image },
  { id: 68, name: "Nur Seha, Amd.Kl", description: 'Kesling',jabatan:'Kesling', image: image },
];

  